name: WebRx
markdown: redcarpet
highliter: rouge
permalinks: pretty
destination: .build
keep_files: ['api']
exclude: ['assets', 'vs']
sass_dir: _sass
encoding: utf-8
excerpt_separator: <!--more-->
asset_bundler:
  compress:
    js: false
    css: false
  base_path: /bundles/
  server_url:
  remove_bundled: false
  dev: false
  bundle_name: false