name: WebRx
markdown: redcarpet
highliter: rouge
permalinks: pretty
destination: .build
exclude: ['assets', 'vs']
encoding: utf-8
excerpt_separator: <!--more-->
assets:
  debug: false
  version: 1
  cachebust: hard
  sources:
    - js
    - css
    - images